"""C header file generator from SoC memory map."""

from amaranth_soc.memory import MemoryMap, BARMemoryMap


__all__ = ["CHeaderGenerator", "generate_bar_header"]


class CHeaderGenerator:
    """Generates C header files from SoC memory map.

    Produces #define macros for:
    - Memory region base addresses and sizes
    - CSR register offsets
    - IRQ numbers
    """

    @staticmethod
    def generate(memory_map, *, base_addr=0):
        """Generate C header content from a MemoryMap.

        Parameters
        ----------
        memory_map : MemoryMap
            The SoC memory map to export.
        base_addr : int
            Base address offset.

        Returns
        -------
        str
            C header file content.
        """
        if not isinstance(memory_map, MemoryMap):
            raise TypeError(f"memory_map must be a MemoryMap, not {memory_map!r}")

        lines = []
        lines.append("#ifndef __SOC_H")
        lines.append("#define __SOC_H")
        lines.append("")
        lines.append("/* Auto-generated by amaranth-soc */")
        lines.append("")

        # Walk memory map windows and generate defines for windows
        for window, name, (start, end, ratio) in memory_map.windows():
            macro_name = "_".join(str(n) for n in name).upper()
            lines.append(f"#define {macro_name}_BASE  0x{start + base_addr:08X}UL")
            lines.append(f"#define {macro_name}_SIZE  0x{end - start:08X}UL")

        # Walk all resources recursively
        for info in memory_map.all_resources():
            macro_name = "_".join(str(n) for n in info.path).upper()
            lines.append(f"#define {macro_name}_BASE  0x{info.start + base_addr:08X}UL")
            lines.append(f"#define {macro_name}_SIZE  0x{info.end - info.start:08X}UL")

        lines.append("")
        lines.append("#endif /* __SOC_H */")
        return "\n".join(lines)

    @staticmethod
    def generate_irq_header(irq_map, *, guard="__SOC_IRQ_H"):
        """Generate C header content for IRQ assignments.

        Parameters
        ----------
        irq_map : dict
            Mapping of IRQ name to IRQ number.
        guard : str
            Include guard macro name.

        Returns
        -------
        str
            C header file content.
        """
        lines = []
        lines.append(f"#ifndef {guard}")
        lines.append(f"#define {guard}")
        lines.append("")
        lines.append("/* Auto-generated IRQ assignments by amaranth-soc */")
        lines.append("")

        for name, number in sorted(irq_map.items(), key=lambda x: x[1]):
            macro_name = name.upper().replace(" ", "_").replace("-", "_")
            lines.append(f"#define IRQ_{macro_name}  {number}")

        lines.append("")
        lines.append(f"#endif /* {guard} */")
        return "\n".join(lines)


def generate_bar_header(bar_map, *, file_name="bar_regs.h"):
    """Generate a C header file with BAR-relative register definitions.

    Parameters
    ----------
    bar_map : BARMemoryMap
        The BAR memory map to generate headers for.
    file_name : str
        Output file name (for the header guard).

    Returns
    -------
    str
        C header file content.
    """
    if not isinstance(bar_map, BARMemoryMap):
        raise TypeError(f"bar_map must be a BARMemoryMap, not {bar_map!r}")

    guard = file_name.upper().replace(".", "_").replace("/", "_").replace("-", "_")
    bar_name = bar_map.name.upper()

    lines = []
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append(f"/* {bar_map.name} Configuration */")
    lines.append(f"#define {bar_name}_SIZE  0x{bar_map.size:X}")
    lines.append(f"#define {bar_name}_INDEX {bar_map.bar_index}")
    lines.append("")
    lines.append("/* Register Offsets (BAR-relative) */")

    for resource, name, (start, end) in bar_map.resources():
        macro_name = "REG_" + "_".join(str(n).upper() for n in name) + "_OFFSET"
        lines.append(f"#define {macro_name} 0x{start:04X}")

    lines.append("")
    lines.append("/* Absolute address macro */")
    lines.append(f"#define {bar_name}_ADDR(base, offset) ((base) + (offset))")
    lines.append("")
    lines.append(f"#endif /* {guard} */")
    return "\n".join(lines)
